import Header from '../../components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import '../../styles/Header.css'
import '../../styles/Home.css'
import '../../styles/cards.css'
import Footer from '../../components/Footer'
import '../../styles/Bag.css'

import {getServerSession} from 'next-auth'
import { SessionProvider } from 'next-auth/react'
import Provider from '../../components/provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TASTROVALdz',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children}) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
         <Provider>
          {children}
         </Provider>
        </body>
    </html>
  )
}
